inherit_from:
- .rubocop_airbnb.yml

LineLength:
  Max: 140

AllCops:
  Exclude:
  - "db/schema.rb"
  - "db/migrate/*"
  - "db/**/*"
  - "bin/*"
  - "config/environments/*"
  - "config/application.rb"
  - "config/initializers/*"
  - "config/spring.rb"
  - "spec/spec_helper.rb"
  - "lib/tasks/*"
  - "vendor/**/*"
  - "path/ruby"
  - "public/**/*"
  - "tmp/**/*"
  - "log/**/*"
  - "app/helpers/notifications_helper.rb"

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Layout/TrailingWhitespace:
  Description: "admit trailing whitespace."
  Enabled: false
