default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  username: postgres
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: RoadVel_development

test:
  <<: *default
  database: RoadVel_test

production:
  adapter: postgresql
  encoding: unicode
  password: 
  pool: 5
  database: RoadVel_production
